# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes/*.bb \
            ${LAYERDIR}/recipes/*.bbappend"

BBFILE_COLLECTIONS += "meta-cos"
BBFILE_PATTERN_meta-cos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cos = "6"

LAYERDEPENDS_meta-cos = "core"
LAYERSERIES_COMPAT_meta-cos = "blacksail wrynose"

IMAGE_INSTALL:append = " libuvc"
IMAGE_INSTALL:append = " tailscale"
IMAGE_INSTALL:append = " rsync"
IMAGE_INSTALL:append = " v4l-utils"
IMAGE_INSTALL:append = " kernel-modules"
IMAGE_INSTALL:append = " l4t-usb-device-mode"
IMAGE_INSTALL:append = " libopencv-videoio"

TOOLCHAIN_TARGET_TASK:append = " libuvc-dev libuvc-staticdev"
TOOLCHAIN_TARGET_TASK:append = " opencv-staticdev"
TOOLCHAIN_TARGET_TASK:append = " allwpilib"
TOOLCHAIN_TARGET_TASK:append = " libeigen-dev"

